classDiagram
  Concept <|-- Level 1
  Concept <|-- Level 2
  Concept <|-- Level 3
  Concept <|-- Level 4
  Concept: Name
  Concept: Colour
  Concept: Position
  Concept: connection
  Concept: +bool z-index
  Concept: +bool CanClick?

  class Level 1{
  current
  transition
  receives
  sends
  }
  class Level 2{
  current
  transition
  receives
  sends

  }
  class Level 3{
  current
  transition
  receives
  sends
  }
  class Level 4{
  current
  transition
  receives
  sends
  }